### ISSUE TITLE
HTTPS-Only Mode

### ISSUE THREAD

**Issue by tillhouse** [ghostery/user-agent-desktop#371] opened 2020-11-19 13:52 UTC
As a Ghostery Browser user, I would like HTTPS-Only Mode to be turned on by default so that all my connections are safe. 

**ACCEPTANCE CRITERIA:**
- The HTTPS-Only Mode should be set to "Enable HTTPS-Only Mode in all windows" by default for all users.

**Comment by sammacbeth** [comment] 2020-11-19 14:06
Duplicate of #367

**Closed by sammacbeth** 2020-11-19 14:06 UTC
