### ISSUE TITLE
Update About License

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#155] opened 2020-09-11 13:43 UTC
`browser/base/content/overrides/app-license.html` https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/base/content/overrides/app-license.html

Relevant commits:
https://github.com/cliqz-oss/browser-f/commit/2c3c33d2ffd647ac9885b86ca1a76ecb4c010cec#diff-176498f5089a9c3b2bacc2970f34c52e
https://github.com/cliqz-oss/browser-f/commit/ae98155d111686f91ed9fb02750384ef85ca11ca#diff-176498f5089a9c3b2bacc2970f34c52e
https://github.com/cliqz-oss/browser-f/commit/945f5074e21eee69b1ed27b2d7221f58e784b3d9#diff-176498f5089a9c3b2bacc2970f34c52e

**Comment by sammacbeth** [comment] 2020-09-14 15:13
Duplicate of #56

**Closed by sammacbeth** 2020-09-14 15:13 UTC
Labels: diffspection
