### ISSUE TITLE
Customize about:network

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#145] opened 2020-09-11 13:41 UTC
`browser/base/content/aboutNetError.js` => https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/base/content/aboutNetError.js#L208

**Comment by chrmod** [comment] 2020-09-15 08:55
Duplicate of https://github.com/ghostery/user-agent-desktop/issues/180

**Closed by chrmod** 2020-09-15 08:55 UTC
Labels: diffspection, require decision
