### ISSUE TITLE
Can't play musics on Spotify web player

### ISSUE THREAD

**Issue by gaeulbyul** [ghostery/user-agent-desktop#477] opened 2021-02-03 00:50 UTC
Environments:
-----

* OS: Microsoft Windows [Version 10.0.19042.746]
* Browser: Ghostery Dawn 2021.01.3 (b75be51) / 64-bit

Steps to reproduce:
-----

1. Visit & login https://open.spotify.com/
2. Try to play music

Expected behavior:
-----

Should play musics normally

Actual behavior:
-----

Doesn't play music, instead...

* Skips to next song immediately. OR
* Music stop at 0:09.

devtools console shows message like:

> Cannot play media. No decoders for requested formats: audio/mp4; codecs="mp4a.40.2", audio/mp4; codecs="mp4a.40.2"

and HTTP 403 Error on `https://gae-spclient.spotify.com/widevine-license/v1/audio/license`

I tried on other web browser (Firefox, MS Edge) and works well there.

![Screenshot](https://user-images.githubusercontent.com/830515/106682062-0f26c200-6605-11eb-975e-67a979602f03.png)

**Comment by 2br-2b** [comment] 2021-02-03 03:14
When you opened Spotify, did you get a message like this:

![screenshot](https://user-images.githubusercontent.com/43968991/106690289-888bc980-659f-11eb-81f7-8d1d82200dc9.png)

? If so, what did you do at this page?

Basically, Wildvine is a proprietary video plugin. You get an option to download it because, unlike the browser, it is not free software. Thus, you have to explicitly opt in to enable support for it.

Spotify requires it to stream music so that it's harder to download the audio from their site.

Looking at https://en.wikipedia.org/wiki/Widevine, there seem to have been some licensing issues with it for other free software programs, so Ghostery browser may be in the same boat.

https://support.mozilla.org/en-US/kb/enable-drm has a bit more info on it.

**Comment by chrmod** [comment] 2021-02-03 10:07
Thank you for great quality bug report. I'm looking into it. 

@gaeulbyul can you please go to `about:addons` to `Plugins` tab and check if Widevine is installed and enabled? 

It should look like this:
<img width="1214" alt="Screenshot 2021-02-03 at 11 05 22" src="https://user-images.githubusercontent.com/1228153/106731550-e0faaf80-660f-11eb-9485-e8dc72e8de37.png">

**Comment by gaeulbyul** [comment] 2021-02-03 10:23
@2br-br, No, I didn't get yellow-bar message. So I checked "DRM Content" section on options page and it was already enabled.

![Screenshot of options page. DRM Content section](https://user-images.githubusercontent.com/830515/106733160-e1696980-6654-11eb-9d41-f0c59dc18c7c.png)

* * *

@chrmod, Same as me. and when I click 3-dot menu button, both plugins are "Always Activate" state.

![List of Plugins](https://user-images.githubusercontent.com/830515/106733234-fa721a80-6654-11eb-8df4-20e99e0c3ca0.png)

**Comment by chrmod** [comment] 2021-02-03 10:47
@gaeulbyul From what I see in your logs http requests for widevine license are failing with 403. Could that be that some content blocker is blocking them? Do you use any addons with Dawn? Maybe you could try to test spotify on a new profile, you can create one in `about:profiles`.

**Comment by gaeulbyul** [comment] 2021-02-03 10:59
I tried with new profile but this problem still exists. I also tried on safe mode (`ghostery.exe -safe-mode`) and not worked either.

**Comment by chrmod** [comment] 2021-02-03 12:51
Was doing some research and it seems other people have same problem with Spotify regardless the browser they use. 
(https://community.spotify.com/t5/Other-Partners-Web-Player-etc/Web-Player-broken-Firefox-and-Chrome/td-p/4839183)

Wonder if that's an effect of a VPN are you maybe Ghostery Midnight user?

**Comment by gaeulbyul** [comment] 2021-02-03 15:43
No, I don’t use Ghostery Midnight or any VPN.

**Comment by gaeulbyul** [comment] 2021-02-04 02:39
Hello, I just tested on Linux virtual machine and works well on there. Is there any difference between Windows version and Linux version?

**Comment by fcjr** [comment] 2021-02-04 18:40
Hey @gaeulbyul we were able to consistently reproduce the issue on our end on windows as well as macOS, we're looking into it now and will update you as soon as we know a bit more!

On linux looks like the codec support lookup is still failing, but the Widevine request succeeds and the songs play fine.  @chrmod Could be related to linux using ffmpeg as a fallback to play Low-Complexity AAC (mp4a.40.2)?

**Comment by yokoffing** [comment] 2021-02-10 20:55
> we were able to consistently reproduce the issue on our end on windows as well as macOS

I can reproduce this as well on Windows 10. Spotify starts to play a song but then goes to the next one. Then repeats this behavior. I pay for a premium plan, so I wouldn't think this is advertisement-related.

**Comment by chrmod** [comment] 2021-02-18 10:33
This is general DRM playback problem, closing the issue in favor of https://github.com/ghostery/user-agent-desktop/issues/506 

@gaeulbyul thank you for your report, it is much appreciated. We will do our best to bring DRM playback to Ghostery Dawn.

**Closed by chrmod** 2021-02-18 10:33 UTC
Labels: bug
