### ISSUE TITLE
Disable Menu Tour

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#148] opened 2020-09-11 13:41 UTC
`browser/base/content/browser-menubar.inc`

https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/base/content/browser-menubar.inc#L473

**Comment by chrmod** [comment] 2020-09-15 09:50
duplicate of https://github.com/ghostery/user-agent-desktop/issues/148

**Comment by sammacbeth** [comment] 2020-09-22 15:23
Fixed in #240

**Closed by sammacbeth** 2020-09-22 15:23 UTC
Labels: diffspection
