### ISSUE TITLE
Extend list of search providers

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#171] opened 2020-09-11 13:47 UTC
Cliqz had an extended list of providers:
`browser/components/search/extensions/list.json`
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/search/extensions/list.json

**Comment by chrmod** [comment] 2020-09-15 09:24
duplicate of https://github.com/ghostery/user-agent-desktop/issues/19

**Closed by chrmod** 2020-09-15 09:24 UTC
Labels: diffspection
