### ISSUE TITLE
Custom migration from Firefox

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#79] opened 2020-08-03 17:47 UTC
I guess it makes sense that there is no migration from Firefox built-in Firefox. There seems to be custom code in Cliqz to handle that and maybe we want to port it?

- [ ] `browser/components/migration/FirefoxProfileMigrator.jsm`: https://github.com/human-web/user-agent-desktop/pull/6/files#diff-99c5cf148fa360ba5fd07905365ca6ba
- [ ] `browser/components/migration/MigrationUtils.jsm` https://github.com/human-web/user-agent-desktop/pull/6/files#diff-a2aeb152915a9ee12b4379f676cff1a6
- [ ] `browser/components/migration/components.conf` https://github.com/human-web/user-agent-desktop/pull/6/files#diff-d83e552c25e683db8ae412ceb3773a28R35-R40

(**Note**: check all changes in the ` browser/components/migration/` folder)

There also seems to be code to allow important from Firefox always, not only on first start: https://github.com/human-web/user-agent-desktop/pull/6/files#diff-a2aeb152915a9ee12b4379f676cff1a6R460-R469

**Comment by chrmod** [comment] 2020-09-15 09:34
Duplicate of https://github.com/ghostery/user-agent-desktop/issues/167

**Closed by chrmod** 2020-09-15 09:34 UTC
Labels: feature: addition
