### ISSUE TITLE
Remove about:logins

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#76] opened 2020-08-03 16:10 UTC
- [ ] https://github.com/human-web/user-agent-desktop/pull/6/files#diff-1eb0c12c4f46fd0466d09616d55bf358R58
- [ ] https://github.com/human-web/user-agent-desktop/pull/6/files#diff-ce805829abadd4f57377251c953b9344R15

**Comment by chrmod** [comment] 2020-09-15 09:35
Duplicate of https://github.com/ghostery/user-agent-desktop/issues/166

**Closed by chrmod** 2020-09-15 09:35 UTC
Labels: feature: deletion
