### ISSUE TITLE
Theme gradient occationally disappears when resizing window

### ISSUE THREAD

**Issue by fcjr** [ghostery/user-agent-desktop#394] opened 2020-11-30 18:21 UTC
On occasion when resizing a window or resizing my screen (attaching a monitor, etc) the gradient of the theme fails to load causing all browser windows to turn purple (the base window color).  This typically occurs when the window is resized via some non-user action (automatically by a window manager like Magnet, or when attaching a monitor).

This seems to be a Firefox bug, but as a temporary solution we might just want to remove the gradient from our theme to "solve" this issue.

**Comment by Melissa-Kay** [comment] 2020-12-08 18:15
Confirming I saw the same issue. I had the issue resizing and bringing back windows from minimized. Also has happened when my monitor disconnects.

**Comment by chrmod** [comment] 2021-01-04 10:03
I was also able to reproduce it on windows. This unfortunately looks like Firefox issue. My hope is that with adoptions of Alpenglow theme the issue will get fix on the upsteam. For Ghostery it's priority decreased as we've changed default theme from Dynamic to Private.

Closing as not actionable.

**Closed by chrmod** 2021-01-04 10:03 UTC
Labels: bug, upstream
