### ISSUE TITLE
Disable Addons Recommendations

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#188] opened 2020-09-11 13:50 UTC
`modules/libpref/init/all.js`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/modules/libpref/init/all.js#L4120

**Comment by chrmod** [comment] 2020-09-14 16:40
duplicate of https://github.com/ghostery/user-agent-desktop/issues/196

**Closed by chrmod** 2020-09-14 16:40 UTC
Labels: diffspection
